blank_issues_enabled: false
contact_links:
  - name:  Documentation
    url: https://github.com/Azure-Samples/azure-nvidia-robotics-reference-architecture#readme
    about: Read the project documentation
  - name: ☁️ Azure Support
    url: https://azure.microsoft.com/support/
    about: For Azure service issues
