apiVersion: omniverse.nvidia.com/v1
kind: ApplicationVersion
metadata:
  name: usd-viewer-107.3.2
  namespace: omni-streaming
  labels:
    app: usd-viewer
    applicationName: usd-viewer
    version: "107.3.2"
spec:
  helm_chart: "ngc-omniverse/kit-appstreaming-session"
  helm_chart_version: "1.11.0"
  container: "nvcr.io/nvidia/omniverse/usd-viewer"
  container_version: "107.3.2"
